# Generated by Django 3.2.5 on 2022-10-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_title', models.TextField(null=True)),
                ('form_body', models.TextField(null=True)),
            ],
        ),
    ]
